### ISSUE TITLE
Debug expressions won't work when launching with binder (runs with Python 3.7)

### ISSUE THREAD

**Issue by rnestler** [The-Compiler/fstring.help#2]
## Bug description

Debug expressions won't work when launching with binder since it starts the environment with Python 3.7

## To Reproduce

 1. Go to https://mybinder.org/v2/gh/The-Compiler/fstring.help/HEAD?labpath=en.ipynb
 2. Try to execute the Debug expressions

## Expected behavior

The binder container should use Python 3.8 and thus the debug expressions should work.

## Screenshots

![screenshot-20220413-140754](https://user-images.githubusercontent.com/1435346/163176671-ee7db126-0dc4-4529-9730-dc48c5c8e366.png)

## Additional context
https://mybinder.readthedocs.io/en/latest/howto/languages.html

**Comment by The-Compiler** [comment]
Hm, still doesn't seem to work, weird.

**Comment by The-Compiler** [comment]
Got it to work in db89d3510a2977c9c0df16314fcd4df075a7624e - looks like they don't support 3.10 yet and the file is just getting silently ignored in that case...
